package ports

import (
	"context"
	"time"

	"github.com/xcreativs/terios/api/internal/domain/identity"
	"github.com/xcreativs/terios/api/internal/domain/payment"
)

// PaymentFilter narrows the practitioner's payments list by creation time.
// Zero values mean "unbounded".
type PaymentFilter struct {
	From *time.Time
	To   *time.Time
}

// Initialization is the result of starting a checkout: the payment record
// plus the gateway's hosted authorization URL the client is redirected to.
type Initialization struct {
	Payment          payment.Payment
	AuthorizationURL string
}

// InitializeParams carries what a transaction is initialized with. Every
// field is server-derived: email from the account, amount/currency from the
// booked service, reference generated by the app layer.
type InitializeParams struct {
	Email      string
	AmountKobo int64
	Currency   string
	Reference  string
}

// InitializedTransaction is what the gateway returns for a new transaction.
type InitializedTransaction struct {
	AuthorizationURL string
	Reference        string
}

// VerifiedTransaction is the server-side truth about a charge, fetched
// from the gateway during webhook confirmation.
type VerifiedTransaction struct {
	Reference  string
	Status     string // gateway status string, e.g. "success"
	AmountKobo int64
	Currency   string
	Channel    string // e.g. "card", "mobile_money"
	PaidAt     time.Time
}

// GatewayError is a typed failure from the payment gateway: either the
// gateway rejected the call (StatusCode set) or it was unreachable.
type GatewayError struct {
	StatusCode int
	Message    string
}

func (e *GatewayError) Error() string { return e.Message }

// PaymentService is the inbound port for the payments slice.
type PaymentService interface {
	// InitializePayment starts a hosted checkout for a booking owned by the
	// caller. Amount, currency, and email are server-derived. Cross-owner
	// access returns booking.ErrBookingNotFound (isolation); a booking with
	// a successful payment returns payment.ErrAlreadyPaid; re-initializing
	// a pending/failed payment reuses the record with a fresh reference.
	InitializePayment(ctx context.Context, id identity.Identity, bookingID string) (Initialization, error)
	// HandlePaystackWebhook processes one raw webhook delivery. The
	// signature is verified against the raw body first
	// (payment.ErrInvalidWebhookSignature). Only verified charge.success
	// events mutate state, idempotently on the payment reference — repeat
	// deliveries, unknown references, and other events are acknowledged
	// without changes.
	HandlePaystackWebhook(ctx context.Context, payload []byte, signature string) error
	// HandleStripeWebhook processes one raw Stripe delivery. The signature
	// is verified against the raw body first
	// (payment.ErrInvalidWebhookSignature). Only verified
	// checkout.session.completed events mutate state, idempotently on the
	// payment reference — repeat deliveries, unknown references, and other
	// events are acknowledged without changes.
	HandleStripeWebhook(ctx context.Context, payload []byte, signature string) error
	// ListMine returns the client's own payments, newest first.
	ListMine(ctx context.Context, clientID string) ([]payment.Payment, error)
	// ListForPractitioner returns payments on the practitioner's bookings,
	// optionally narrowed by creation time, newest first.
	ListForPractitioner(ctx context.Context, practitionerID string, filter PaymentFilter) ([]payment.Payment, error)
	// RefundPayment refunds a successful payment on one of the
	// practitioner's bookings. Non-success payments return
	// payment.ErrInvalidTransition; cross-practitioner access returns
	// payment.ErrPaymentNotFound (isolation).
	RefundPayment(ctx context.Context, practitionerID, paymentID string) (payment.Payment, error)
}

// PaymentRepository is the outbound port for payment persistence.
type PaymentRepository interface {
	// Create persists a new payment, assigning its ID. A second record for
	// the same booking (unique index) returns payment.ErrAlreadyPaid.
	Create(ctx context.Context, p payment.Payment) (payment.Payment, error)
	// FindByID looks up a payment by id; misses return
	// payment.ErrPaymentNotFound.
	FindByID(ctx context.Context, id string) (payment.Payment, error)
	// FindByBookingID looks up the booking's single payment; misses return
	// payment.ErrPaymentNotFound.
	FindByBookingID(ctx context.Context, bookingID string) (payment.Payment, error)
	// FindByReference looks up a payment by its gateway reference — the
	// webhook join key; misses return payment.ErrPaymentNotFound.
	FindByReference(ctx context.Context, reference string) (payment.Payment, error)
	// Update persists a payment's mutable state. Misses return
	// payment.ErrPaymentNotFound.
	Update(ctx context.Context, p payment.Payment) (payment.Payment, error)
	// ListByClient returns the client's payments ordered by createdAt
	// descending (newest first).
	ListByClient(ctx context.Context, clientID string) ([]payment.Payment, error)
	// ListByBookingIDs returns payments for the given bookings matching the
	// creation-time filter, ordered by createdAt descending. The payments
	// collection carries no practitionerId (index design is fixed), so the
	// practitioner view joins through the caller's booking ids.
	ListByBookingIDs(ctx context.Context, bookingIDs []string, filter PaymentFilter) ([]payment.Payment, error)
}

// PaymentGateway is the outbound port for the payment provider (Paystack
// or Stripe, selected by configuration). Card and mobile-money details
// only ever exist on the provider's hosted checkout — this port deals in
// references and amounts only.
type PaymentGateway interface {
	// Initialize creates a transaction and returns the hosted checkout URL.
	Initialize(ctx context.Context, params InitializeParams) (InitializedTransaction, error)
	// Verify fetches the provider-side truth about a transaction.
	Verify(ctx context.Context, reference string) (VerifiedTransaction, error)
	// Refund refunds a successful transaction by reference.
	Refund(ctx context.Context, reference string) error
	// VerifyWebhookSignature reports whether signature authenticates the
	// raw webhook payload under the provider's signing scheme, compared in
	// constant time.
	VerifyWebhookSignature(payload []byte, signature string) bool
}
