sonar.projectKey=terios-api
sonar.projectName=Terios API
sonar.sources=cmd,internal
sonar.tests=cmd,internal
sonar.test.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
sonar.exclusions=**/vendor/**,**/bin/**
